### ISSUE TITLE
Coinflip Gamble Bot Using Martingale Method

### ISSUE THREAD

**Issue by overfy** [ahihiyou20/OwO-Gamble#1]
Hello, i have suggestion to build a owo coin flip bot using martingale method, and i hope you can make it :(

Here's the logic that i use to gamble a coinflip in owo

start bet on 100 cowoncy / 250 cowoncy
if we lose the bet, increase bet 2.5 / 3 times untill we win, if we win, bet back to the first start.
if the first bet are win, the bet didn't change, bet only change if we lose.

why we only bet using 100 / 250 cowoncy ? because if we bet to high at start, the probability to lose is more higher because maximum bet in owo only 150k cowoncy

sorry for my bad english. thankyou.

**Comment by ahihiyou20** [comment]
> Hello, i have suggestion to build a owo coin flip bot using martingale method, and i hope you can make it :(
> 
> Here's the logic that i use to gamble a coinflip in owo
> 
> start bet on 100 cowoncy / 250 cowoncy if we lose the bet, increase bet 2.5 / 3 times untill we win, if we win, bet back to the first start. if the first bet are win, the bet didn't change, bet only change if we lose.
> 
> why we only bet using 100 / 250 cowoncy ? because if we bet to high at start, the probability to lose is more higher because maximum bet in owo only 150k cowoncy
> 
> sorry for my bad english. thankyou.

Bruh the selfbot is actually using that method. Start bet with 1000, if lose then x2 the cowoncy untill you win. After you win then start bet at 1000 again. And bet only change if you lose also.
The different is: the selfbot bet 1000 instead of 100 cowoncy so maybe it will give more cowoncy.

**Comment by overfy** [comment]
thankyou bro :D
